services:
  postgres:
    image: postgres:latest
    container_name: postgres-stock
    environment:
      POSTGRES_DB: estoque-db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  stock-app:
    build: .
    container_name: stock-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/estoque-db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECURITY_CONFIG_KEY: ${SECURITY_CONFIG_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: