CREATE TABLE operations
(
    operation_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    operation_type VARCHAR(255),
    date_time      TIMESTAMP WITHOUT TIME ZONE,
    product_id     BIGINT,
    stock_id       BIGINT,
    CONSTRAINT pk_operations PRIMARY KEY (operation_id)
);

CREATE TABLE products
(
    product_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    description    OID,
    purchase_price DECIMAL(13, 2),
    sale_price     DECIMAL(13, 2),
    quantity       INTEGER,
    stock_id       BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

CREATE TABLE roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE stocks
(
    stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_stocks PRIMARY KEY (stock_id)
);

CREATE TABLE stores
(
    store_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    address  VARCHAR(255),
    stock_id BIGINT,
    CONSTRAINT pk_stores PRIMARY KEY (store_id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_stock UNIQUE (stock_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE operations
    ADD CONSTRAINT FK_OPERATIONS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (product_id);

ALTER TABLE operations
    ADD CONSTRAINT FK_OPERATIONS_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stocks (stock_id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stocks (stock_id);

ALTER TABLE stores
    ADD CONSTRAINT FK_STORES_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stocks (stock_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);